# Site wide configuration

title: "Trilok Tourani"
description: "Trilok Tourani's personal website. This is where Trilok's thoughts, research, projects, campaigns, contribution and blog posts go."
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://triloktourani.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: "Trilok Tourani"
  email: "triloktourani17@gmail.com"
  twitter: "-"
  google:
    ad-client: 
    ad-slot: 
  bio: "Student Developer at FOSSASIA (Google Summer of Code)"
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: "trilok"


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
