# Site wide configuration

title: "Trilok Tourani" 
description: "Trilok Tourani's personal website. This is where Trilok's thoughts, research, projects, campaigns, contribution and blog posts go. 
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //d4r3topk.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Trilok Tourani
  web: http://d4r3topk.github.io
  email: triloktourani17@gmail.com
  twitter: -
  bio: ""
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
  disqus-shortname:trilok


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
